// <auto-generated />
using MantenimientoTic.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MantenimientoTic.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20220830234713_tablasEntidades")]
    partial class tablasEntidades
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MantenimientoTic.App.Dominio.Cliente", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("MantenimientoTic.App.Dominio.EstadoEntrada", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DescripcionEntrada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoEntradaAceite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoEntradaAire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoEntradaFiltro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaEntrada")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadosEntrada");
                });

            modelBuilder.Entity("MantenimientoTic.App.Dominio.EstadoSalida", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DescripcionEntrada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoEntradaAceite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoEntradaAire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoEntradaFiltro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaEntrada")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadosSalida");
                });

            modelBuilder.Entity("MantenimientoTic.App.Dominio.Historico", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Historicos");
                });

            modelBuilder.Entity("MantenimientoTic.App.Dominio.Loguin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("MantenimientoTic.App.Dominio.Mantenimiento", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DecripcionMantenimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaMantenimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoMantenimiento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("MantenimientoTic.App.Dominio.Persona", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("MantenimientoTic.App.Dominio.Repuesto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FechaCambio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreRepuesto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Repuestos");
                });

            modelBuilder.Entity("MantenimientoTic.App.Dominio.Tecnico", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Tecnicos");
                });

            modelBuilder.Entity("MantenimientoTic.App.Dominio.Vehiculo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
